<?php

use Illuminate\Database\Seeder;
use App\Eloquent\Post;

class PostsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Post::truncate();
        Post::create([
            'ceo_title' => '5 Tips For Real Estate Photography',
            'name' => '5 Tips For Real Estate Photography',
            'image_src' => 'seeds/blog/blog-01.jpg',
            'image_title' => 'seeds/blog/blog-01.jpg',
            'ceo_description' => 'Using quality photos in your real estate listing is essential when selling a property. Better photos generate more interest which potentially equates to more dollars. This article covers 5 essential tips that make shooting and selling a home easier.',
            'description' => '<p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">Taking quality photos is a difficult skill and can be even harder when you put real estate into the mix. Often with real estate photography, you have to work with unfavorable conditions and time constraints, which can mean you photos don’t always turn out quite as expected.</p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">Most professional real estate photographers will provide the home occupants and the agent with a&nbsp;<a href="https://dung13890.github.io/blog-detail.html#" style="color: rgb(241, 197, 90); transition: color 0.2s ease-in-out 0s;">checklist</a>&nbsp;of things they need to do to get the property ready for photography. Often, a listing may not be ready for photos, so you’ll just have to work with it, hope for the best and edit the images later. Most professional photographers edit their photos in the post producing process which is time-consuming and technical, this is where outsourcing the editing process is beneficial for both the photographer and the real estate agent.</p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"=""><img alt="" src="https://dung13890.github.io/images/post1.jpg" style="border-width: initial; border-style: none; max-width: 100%; display: block; width: 100%;"></p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">With the advances in photo editing software items within a photo can now be easily and quickly removed, as if it was never there. Using item removal on your listing photos benefits both Real Estate Agents and Property Managers, here are just some of the benefits:</p>',
        ]);
        Post::create([
            'ceo_title' => 'WHAT ARE CROP SENSORS, FIELD OF VIEW & APERTURE?',
            'name' => 'WHAT ARE CROP SENSORS, FIELD OF VIEW & APERTURE?',
            'image_src' => 'seeds/blog/blog-02.jpg',
            'image_title' => 'seeds/blog/blog-02.jpg',
            'ceo_description' => 'So, you’re in the market for a camera, but have no idea what to buy and are faced with a mountain of jargon that makes absolutely no sense, you’re not alone!... But we have an explanation.',
            'description' => '<p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">Taking quality photos is a difficult skill and can be even harder when you put real estate into the mix. Often with real estate photography, you have to work with unfavorable conditions and time constraints, which can mean you photos don’t always turn out quite as expected.</p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">Most professional real estate photographers will provide the home occupants and the agent with a&nbsp;<a href="https://dung13890.github.io/blog-detail.html#" style="color: rgb(241, 197, 90); transition: color 0.2s ease-in-out 0s;">checklist</a>&nbsp;of things they need to do to get the property ready for photography. Often, a listing may not be ready for photos, so you’ll just have to work with it, hope for the best and edit the images later. Most professional photographers edit their photos in the post producing process which is time-consuming and technical, this is where outsourcing the editing process is beneficial for both the photographer and the real estate agent.</p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"=""><img alt="" src="https://dung13890.github.io/images/post1.jpg" style="border-width: initial; border-style: none; max-width: 100%; display: block; width: 100%;"></p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">With the advances in photo editing software items within a photo can now be easily and quickly removed, as if it was never there. Using item removal on your listing photos benefits both Real Estate Agents and Property Managers, here are just some of the benefits:</p>',
        ]);
        Post::create([
            'ceo_title' => 'FAST & EASY HDR PHOTOGRAPHY TIPS FOR REAL ESTATE',
            'name' => 'FAST & EASY HDR PHOTOGRAPHY TIPS FOR REAL ESTATE',
            'image_src' => 'seeds/blog/blog-03.jpg',
            'image_title' => 'seeds/blog/blog-03.jpg',
            'ceo_description' => 'At we-edit.com.vn we’re all about making the lives of property professionals and photographers easier. Therefore, we have put together some simple things to follow to make taking HDR (High-Dynamic Range) real estate photos easy.',
            'description' => '<p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">Taking quality photos is a difficult skill and can be even harder when you put real estate into the mix. Often with real estate photography, you have to work with unfavorable conditions and time constraints, which can mean you photos don’t always turn out quite as expected.</p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">Most professional real estate photographers will provide the home occupants and the agent with a&nbsp;<a href="https://dung13890.github.io/blog-detail.html#" style="color: rgb(241, 197, 90); transition: color 0.2s ease-in-out 0s;">checklist</a>&nbsp;of things they need to do to get the property ready for photography. Often, a listing may not be ready for photos, so you’ll just have to work with it, hope for the best and edit the images later. Most professional photographers edit their photos in the post producing process which is time-consuming and technical, this is where outsourcing the editing process is beneficial for both the photographer and the real estate agent.</p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"=""><img alt="" src="https://dung13890.github.io/images/post1.jpg" style="border-width: initial; border-style: none; max-width: 100%; display: block; width: 100%;"></p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">With the advances in photo editing software items within a photo can now be easily and quickly removed, as if it was never there. Using item removal on your listing photos benefits both Real Estate Agents and Property Managers, here are just some of the benefits:</p>',
        ]);
        Post::create([
            'ceo_title' => 'WHEN TO USE AN ITEM REMOVAL EDIT ON PHOTOS',
            'name' => 'WHEN TO USE AN ITEM REMOVAL EDIT ON PHOTOS',
            'image_src' => 'seeds/blog/blog-04.jpg',
            'image_title' => 'seeds/blog/blog-04.jpg',
            'ceo_description' => 'Other than the essential, Image Enhancement edit, using Item Removal on images can be one of the most important, changing the whole look and feel of a shot. Often a forgotten edit by many Property Professionals but an easy solution to many listing woes.',
            'description' => '<p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">Taking quality photos is a difficult skill and can be even harder when you put real estate into the mix. Often with real estate photography, you have to work with unfavorable conditions and time constraints, which can mean you photos don’t always turn out quite as expected.</p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">Most professional real estate photographers will provide the home occupants and the agent with a&nbsp;<a href="https://dung13890.github.io/blog-detail.html#" style="color: rgb(241, 197, 90); transition: color 0.2s ease-in-out 0s;">checklist</a>&nbsp;of things they need to do to get the property ready for photography. Often, a listing may not be ready for photos, so you’ll just have to work with it, hope for the best and edit the images later. Most professional photographers edit their photos in the post producing process which is time-consuming and technical, this is where outsourcing the editing process is beneficial for both the photographer and the real estate agent.</p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"=""><img alt="" src="https://dung13890.github.io/images/post1.jpg" style="border-width: initial; border-style: none; max-width: 100%; display: block; width: 100%;"></p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">With the advances in photo editing software items within a photo can now be easily and quickly removed, as if it was never there. Using item removal on your listing photos benefits both Real Estate Agents and Property Managers, here are just some of the benefits:</p>',
        ]);
        Post::create([
            'ceo_title' => '5 Tips For Real Estate Photography',
            'name' => '5 Tips For Real Estate Photography',
            'image_src' => 'seeds/blog/blog-05.jpg',
            'image_title' => 'seeds/blog/blog-05.jpg',
            'ceo_description' => 'Using quality photos in your real estate listing is essential when selling a property. Better photos generate more interest which potentially equates to more dollars. This article covers 5 essential tips that make shooting and selling a home easier.',
            'description' => '<p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">Taking quality photos is a difficult skill and can be even harder when you put real estate into the mix. Often with real estate photography, you have to work with unfavorable conditions and time constraints, which can mean you photos don’t always turn out quite as expected.</p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">Most professional real estate photographers will provide the home occupants and the agent with a&nbsp;<a href="https://dung13890.github.io/blog-detail.html#" style="color: rgb(241, 197, 90); transition: color 0.2s ease-in-out 0s;">checklist</a>&nbsp;of things they need to do to get the property ready for photography. Often, a listing may not be ready for photos, so you’ll just have to work with it, hope for the best and edit the images later. Most professional photographers edit their photos in the post producing process which is time-consuming and technical, this is where outsourcing the editing process is beneficial for both the photographer and the real estate agent.</p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"=""><img alt="" src="https://dung13890.github.io/images/post1.jpg" style="border-width: initial; border-style: none; max-width: 100%; display: block; width: 100%;"></p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">With the advances in photo editing software items within a photo can now be easily and quickly removed, as if it was never there. Using item removal on your listing photos benefits both Real Estate Agents and Property Managers, here are just some of the benefits:</p>',
        ]);
        Post::create([
            'ceo_title' => 'WHAT ARE CROP SENSORS, FIELD OF VIEW & APERTURE?',
            'name' => 'WHAT ARE CROP SENSORS, FIELD OF VIEW & APERTURE?',
            'image_src' => 'seeds/blog/blog-06.jpg',
            'image_title' => 'seeds/blog/blog-06.jpg',
            'ceo_description' => 'So, you’re in the market for a camera, but have no idea what to buy and are faced with a mountain of jargon that makes absolutely no sense, you’re not alone!... But we have an explanation.',
            'description' => '<p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">Taking quality photos is a difficult skill and can be even harder when you put real estate into the mix. Often with real estate photography, you have to work with unfavorable conditions and time constraints, which can mean you photos don’t always turn out quite as expected.</p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">Most professional real estate photographers will provide the home occupants and the agent with a&nbsp;<a href="https://dung13890.github.io/blog-detail.html#" style="color: rgb(241, 197, 90); transition: color 0.2s ease-in-out 0s;">checklist</a>&nbsp;of things they need to do to get the property ready for photography. Often, a listing may not be ready for photos, so you’ll just have to work with it, hope for the best and edit the images later. Most professional photographers edit their photos in the post producing process which is time-consuming and technical, this is where outsourcing the editing process is beneficial for both the photographer and the real estate agent.</p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"=""><img alt="" src="https://dung13890.github.io/images/post1.jpg" style="border-width: initial; border-style: none; max-width: 100%; display: block; width: 100%;"></p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">With the advances in photo editing software items within a photo can now be easily and quickly removed, as if it was never there. Using item removal on your listing photos benefits both Real Estate Agents and Property Managers, here are just some of the benefits:</p>',
        ]);
        if (App::environment('local')) {
            factory(Post::class, 0)->create();
        }
    }
}
