version: "2"

services:
  application:
    image: debian
    volumes:
      - ./:/var/www/app
  workspace:
    image: dung13890/laravel-env
    restart: always
    volumes_from:
      - application
    tty: true
    links:
     - mysql
  mysql:
    restart: always
    image: mariadb
    volumes:
      - ./.docker/mariadb:/var/lib/mysql
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8000:8080
  redis:
      restart: always
      image: redis:latest
      expose:
        - "6379"
      volumes:
        - ./.docker/redis:/data
  caddy:
    image: abiosoft/caddy
    restart: always
    volumes_from:
      - application
    ports:
      - "80:80"
      - "443:443"
    command: ["--conf", "/var/www/app/Caddyfile", "--log", "stdout"]
